CREATE TABLE Transactions (
    TransactionId UNIQUEIDENTIFIER PRIMARY KEY,
    Status VARCHAR(50) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    ConfirmedAt DATETIME NULL,
    MerchantId UNIQUEIDENTIFIER NOT NULL
);

CREATE TABLE TransactionItems (
    ItemId UNIQUEIDENTIFIER PRIMARY KEY,
    TransactionId UNIQUEIDENTIFIER NOT NULL,
    Description VARCHAR(255),
    Amount DECIMAL(18,2) NOT NULL,
    FOREIGN KEY (TransactionId) REFERENCES Transactions(TransactionId)
);

CREATE TABLE Payments (
    PaymentId UNIQUEIDENTIFIER PRIMARY KEY,
    TransactionId UNIQUEIDENTIFIER NOT NULL,
    Status VARCHAR(50) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    ConfirmedAt DATETIME NULL,
    FOREIGN KEY (TransactionId) REFERENCES Transactions(TransactionId)
);

CREATE TABLE OutboxMessages (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    EventType VARCHAR(100) NOT NULL,
    Payload NVARCHAR(MAX) NOT NULL,
    OccurredOn DATETIME NOT NULL DEFAULT GETDATE(),
    Processed BIT NOT NULL DEFAULT 0
);
